/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author pedro
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jItemMenuCliente = new javax.swing.JMenuItem();
        jItemMenuServiços = new javax.swing.JMenuItem();
        jItemMenuUsuario = new javax.swing.JMenuItem();
        jMenuOperacao = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuItemRelatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/FundoMenuPrincipal.jpg"))); // NOI18N

        jMenuCadastro.setText("Cadastro");

        jItemMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/cliente3.png"))); // NOI18N
        jItemMenuCliente.setText("Clientes");
        jMenuCadastro.add(jItemMenuCliente);

        jItemMenuServiços.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/Serviço.png"))); // NOI18N
        jItemMenuServiços.setText("Serviços");
        jMenuCadastro.add(jItemMenuServiços);

        jItemMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/user.png"))); // NOI18N
        jItemMenuUsuario.setText("Usuario");
        jItemMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemMenuUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jItemMenuUsuario);

        jMenuBar1.add(jMenuCadastro);

        jMenuOperacao.setText("Operação");
        jMenuBar1.add(jMenuOperacao);

        jMenuRelatorio.setText("Relatório");

        jMenuItemRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/relatorio (2).png"))); // NOI18N
        jMenuItemRelatorio.setText("Relatorios");
        jMenuItemRelatorio.setToolTipText("");
        jMenuRelatorio.add(jMenuItemRelatorio);

        jMenuBar1.add(jMenuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblFundo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblFundo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jItemMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemMenuUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jItemMenuUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jItemMenuCliente;
    private javax.swing.JMenuItem jItemMenuServiços;
    private javax.swing.JMenuItem jItemMenuUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemRelatorio;
    private javax.swing.JMenu jMenuOperacao;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JLabel jlblFundo;
    // End of variables declaration//GEN-END:variables
}
